name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # o main, según tu rama principal

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 🧲 Checkout repo
      uses: actions/checkout@v3

    - name: 🚀 Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: pdgv1979  # nombre exacto de tu Web App
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .  # carpeta raíz del proyecto (donde está informacion.html)

  build-and-test:
    needs: build-and-deploy  # 👈 Esto fuerza a esperar que se complete el job anterior  
    runs-on: windows-latest

    steps:
    - name: 🧲 Checkout repo
      uses: actions/checkout@v3

    - name: 🔧 Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # ajusta según la versión que uses

    - name: 📦 Restore dependencies
      run: dotnet restore test\testsolu

    - name: 🛠️ Build project
      run: dotnet build test\testsolu --configuration Release

    - name: 🧪 Run NUnit tests
      run: dotnet test  test\testsolu --no-build --verbosity normal