# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - pdgv19790707

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  deploy:
    runs-on: windows-latest

    
    steps:
      - uses: actions/checkout@v4

      - name: Upload static files
        run: |
          mkdir deploy
          cp -r * deploy
          echo "Archivos copiados para despliegue"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pdgv19790707'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37C7803E78B34A2F9F0C32517D376E47 }}